name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # tous les jours à minuit
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: linkoro57
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "update snake" || echo "No changes to commit"
          git push
